name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint 🧹
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: yarn lint
      - run: yarn format:check

  typecheck:
    name: Typecheck 🔎
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: yarn typecheck

  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: yarn test --maxWorkers=2 --coverage

  build:
    name: Build package 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: yarn prepare
      - name: Check the published file list
        run: yarn pack --dry-run
